# Generated by Django 4.2.4 on 2023-08-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_cd', models.CharField(max_length=10)),
                ('movie_nm', models.CharField(max_length=200)),
                ('genre_nm', models.CharField(max_length=100)),
            ],
        ),
    ]
