# Generated by Django 4.2.4 on 2023-08-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(default='https://example.com/default.jpg', max_length=300),
        ),
    ]
